export type SortCategoryValues =
    "popularity.asc"
    | "popularity.desc"
    | "revenue.asc"
    | "revenue.desc"
    | "primary_release_date.asc"
    | "primary_release_date.desc"
    | "vote_average.asc"
    | "vote_average.desc"
    | "original_title.asc"
    | "original_title.desc"